-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2020-03-05 14:17:14 EST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE contents (
    id                INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    content_edition   VARCHAR2(50) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    stix_id           VARCHAR2(255) NOT NULL,
    file_size         INTEGER NOT NULL,
    job_id            INTEGER NOT NULL,
    mime_type         VARCHAR2(255) NOT NULL,
    raw_content       BLOB,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    uploaded_from     VARCHAR2(30) DEFAULT 'API' NOT NULL
)
LOGGING;

ALTER TABLE contents ADD CONSTRAINT contents_pk PRIMARY KEY ( id );

CREATE TABLE error_messages (
    id            INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description   CLOB,
    is_warning    CHAR(1) DEFAULT '0' NOT NULL,
    job_id        INTEGER
)
LOGGING;

ALTER TABLE error_messages ADD CONSTRAINT error_messages_pk PRIMARY KEY ( id );

CREATE TABLE human_review_fields (
    id                     INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    field_name             VARCHAR2(50) NOT NULL,
    field_value_original   CLOB,
    has_pii                CHAR(1) NOT NULL,
    human_review_id        INTEGER NOT NULL,
    is_changed             CHAR(1) DEFAULT '0' NOT NULL,
    object_name            VARCHAR2(255)
)
LOGGING;

ALTER TABLE human_review_fields ADD CONSTRAINT human_review_fields_pk PRIMARY KEY ( id );

CREATE TABLE human_review_revisions (
    id                    INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    field_value_revised   CLOB,
    reason                VARCHAR2(255),
    field_id              INTEGER NOT NULL,
    is_active             CHAR(1) DEFAULT '1' NOT NULL,
    user_id               INTEGER NOT NULL
)
LOGGING;

ALTER TABLE human_review_revisions ADD CONSTRAINT human_review_revisions_pk PRIMARY KEY ( id );

CREATE TABLE human_reviews (
    id                       INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    approved_at              TIMESTAMP,
    approved_by              INTEGER,
    fields_count             INTEGER DEFAULT 0 NOT NULL,
    fields_count_completed   INTEGER DEFAULT 0 NOT NULL,
    job_id                   INTEGER NOT NULL,
    locked_at                TIMESTAMP,
    locked_by                INTEGER,
    submitted_at             TIMESTAMP,
    submitted_by             INTEGER
)
LOGGING;

ALTER TABLE human_reviews ADD CONSTRAINT human_reviews_pk PRIMARY KEY ( id );

CREATE TABLE jobs (
    id                   INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at             TIMESTAMP,
    instance             VARCHAR2(255) NOT NULL,
    needs_review         CHAR(1) DEFAULT '1' NOT NULL,
    originating_job_id   INTEGER,
    priority             VARCHAR2(255),
    started_at           TIMESTAMP,
    status               CHAR(1) DEFAULT 'N' NOT NULL,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id              INTEGER NOT NULL
)
LOGGING;

ALTER TABLE jobs ADD CONSTRAINT jobs_pk PRIMARY KEY ( id );

CREATE TABLE out_queue (
    id            INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    destination   VARCHAR2(255) NOT NULL,
    file_type     VARCHAR2(255) NOT NULL,
    job_id        INTEGER NOT NULL
)
LOGGING;

ALTER TABLE out_queue ADD CONSTRAINT out_queue_pk PRIMARY KEY ( id );

CREATE TABLE "PRIVILEGES" (
    id            INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    description   VARCHAR2(255),
    name          VARCHAR2(255)
)
LOGGING;

ALTER TABLE "PRIVILEGES" ADD CONSTRAINT privileges_pk PRIMARY KEY ( id );

CREATE TABLE role_privileges (
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     INTEGER NOT NULL,
    privilege_id   INTEGER NOT NULL,
    role_id        INTEGER NOT NULL
)
LOGGING;

ALTER TABLE role_privileges ADD CONSTRAINT role_privileges_pk PRIMARY KEY ( privilege_id,
                                                                            role_id );

CREATE TABLE roles (
    id            INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    INTEGER NOT NULL,
    description   VARCHAR2(255),
    name          VARCHAR2(255) NOT NULL,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by    INTEGER NOT NULL
)
LOGGING;

ALTER TABLE roles ADD CONSTRAINT roles_pk PRIMARY KEY ( id );

CREATE TABLE status_lookup (
    id            INTEGER NOT NULL,
    status_code   CHAR(1) NOT NULL,
    name          VARCHAR2(255) NOT NULL,
    description   VARCHAR2(255) NOT NULL
)
LOGGING;

ALTER TABLE status_lookup ADD CONSTRAINT status_lookup_pk PRIMARY KEY ( id );

CREATE TABLE traceability_transfer (
    id                  INTEGER NOT NULL,
    last_produced_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
LOGGING;

ALTER TABLE traceability_transfer ADD CONSTRAINT traceability_transfer_pk PRIMARY KEY ( id );

CREATE TABLE user_roles (
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   INTEGER NOT NULL,
    role_id      INTEGER NOT NULL,
    user_id      INTEGER NOT NULL
)
LOGGING;

ALTER TABLE user_roles ADD CONSTRAINT user_roles_pk PRIMARY KEY ( role_id,
                                                                  user_id );

CREATE TABLE user_sessions (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    session_id   VARCHAR2(255) NOT NULL,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    username     VARCHAR2(255) NOT NULL
)
LOGGING;

CREATE INDEX session_id ON
    user_sessions (
        session_id
    ASC )
        LOGGING;

ALTER TABLE user_sessions ADD CONSTRAINT user_sessions_pk PRIMARY KEY ( id );

CREATE TABLE users (
    id                         INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    api_key                    VARCHAR2(255),
    api_key_secret_encrypted   BLOB,
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    first_name                 VARCHAR2(255),
    is_deleted                 CHAR(1) DEFAULT '0' NOT NULL,
    is_disabled                CHAR(1) DEFAULT '0' NOT NULL,
    last_name                  VARCHAR2(255),
    password_encrypted         BLOB,
    updated_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    username                   VARCHAR2(255) NOT NULL
)
LOGGING;

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id );

ALTER TABLE users ADD CONSTRAINT api_key UNIQUE ( api_key );

ALTER TABLE users ADD CONSTRAINT username UNIQUE ( username );

ALTER TABLE contents
    ADD CONSTRAINT fk_contents_job FOREIGN KEY ( job_id )
        REFERENCES jobs ( id )
    NOT DEFERRABLE;

ALTER TABLE error_messages
    ADD CONSTRAINT fk_errors_job FOREIGN KEY ( job_id )
        REFERENCES jobs ( id )
    NOT DEFERRABLE;

ALTER TABLE human_reviews
    ADD CONSTRAINT fk_hr_job FOREIGN KEY ( job_id )
        REFERENCES jobs ( id )
    NOT DEFERRABLE;

ALTER TABLE human_reviews
    ADD CONSTRAINT fk_hrappr_user FOREIGN KEY ( approved_by )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE human_review_fields
    ADD CONSTRAINT fk_hrf_hr FOREIGN KEY ( human_review_id )
        REFERENCES human_reviews ( id )
    NOT DEFERRABLE;

ALTER TABLE human_reviews
    ADD CONSTRAINT fk_hrlock_user FOREIGN KEY ( locked_by )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE human_review_revisions
    ADD CONSTRAINT fk_hrr_hr FOREIGN KEY ( field_id )
        REFERENCES human_review_fields ( id )
    NOT DEFERRABLE;

ALTER TABLE human_review_revisions
    ADD CONSTRAINT fk_hrr_user FOREIGN KEY ( user_id )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE human_reviews
    ADD CONSTRAINT fk_hrsubm_user FOREIGN KEY ( submitted_by )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE jobs
    ADD CONSTRAINT fk_jobs_users FOREIGN KEY ( user_id )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE out_queue
    ADD CONSTRAINT fk_outq_job FOREIGN KEY ( job_id )
        REFERENCES jobs ( id )
    NOT DEFERRABLE;

ALTER TABLE role_privileges
    ADD CONSTRAINT fk_rolepriv_priv FOREIGN KEY ( privilege_id )
        REFERENCES "PRIVILEGES" ( id )
    NOT DEFERRABLE;

ALTER TABLE role_privileges
    ADD CONSTRAINT fk_rolepriv_role FOREIGN KEY ( role_id )
        REFERENCES roles ( id )
    NOT DEFERRABLE;

ALTER TABLE roles
    ADD CONSTRAINT fk_roles_created_by FOREIGN KEY ( created_by )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE roles
    ADD CONSTRAINT fk_roles_updated_by FOREIGN KEY ( updated_by )
        REFERENCES users ( id )
    NOT DEFERRABLE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userrole_role FOREIGN KEY ( role_id )
        REFERENCES roles ( id )
    NOT DEFERRABLE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userrole_user FOREIGN KEY ( user_id )
        REFERENCES users ( id )
    NOT DEFERRABLE;





-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             1
-- ALTER TABLE                             51
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
