DROP TABLE hradmin.contents CASCADE CONSTRAINTS;
DROP TABLE hradmin.error_messages CASCADE CONSTRAINTS;
DROP TABLE hradmin.human_review_fields CASCADE CONSTRAINTS;
DROP TABLE hradmin.human_review_revisions CASCADE CONSTRAINTS;
DROP TABLE hradmin.human_reviews CASCADE CONSTRAINTS;
DROP TABLE hradmin.jobs CASCADE CONSTRAINTS;
DROP TABLE hradmin.out_queue CASCADE CONSTRAINTS;
DROP TABLE hradmin."PRIVILEGES" CASCADE CONSTRAINTS;
DROP TABLE hradmin.role_privileges CASCADE CONSTRAINTS;
DROP TABLE hradmin.roles CASCADE CONSTRAINTS;
DROP TABLE hradmin.status_lookup CASCADE CONSTRAINTS;
DROP TABLE hradmin.traceability_transfer CASCADE CONSTRAINTS;
DROP TABLE hradmin.user_roles CASCADE CONSTRAINTS;
DROP TABLE hradmin.user_sessions CASCADE CONSTRAINTS;
DROP TABLE hradmin.users CASCADE CONSTRAINTS;

PURGE RECYCLEBIN